= your-link API Documentation
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[link-api]]
== 링크 API

[[링크-생성]]
=== 링크 생성

operation::create-link[snippets='http-request,query-parameters,request-fields,http-response,response-fields']

[[링크-수정]]
=== 링크 수정

operation::update-link[snippets='http-request,query-parameters,request-fields,http-response,response-fields']

[[단일-링크-조회]]
=== 단일 링크 조회

operation::get-link[snippets='http-request,query-parameters,http-response,response-fields']

[[링크-목록-조회]]
=== 링크 목록 조회

operation::get-links[snippets='http-request,query-parameters,http-response,response-fields']

[[member-api]]
== 멤버 API

[[멤버-생성]]
=== 멤버 생성

operation::create-member[snippets='http-request,request-fields,http-response,response-fields']

[[tag-API]]
== 태그 API

[[링크별-태그-조회]]
=== 링크별 태그 조회

operation::get-tags-by-link[snippets='http-request,query-parameters,http-response,response-fields']

[[link-stat-api]]
== 링크 통계 API

[[총-링크-개수-조회]]
=== 총 링크 개수 조회

operation::get-link-count[snippets='http-request,http-response,response-fields']

[[auth-API]]
== 인증/인가 API

[[로그인]]
=== 로그인

operation::login[snippets='http-request,request-fields,http-response,response-fields']
